version: "3.8"

services:
  icarus-edge-detector:
    build:
      context: icarus-edge-detector
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=nvcr.io/nvidia/l4t-ml:r32.7.1-py3
    image: cricarusprod001.azurecr.io/icarus-edge-detector:${BUILD_VERSION:-latest}