version: "3.8"

services:
  icarus-detector:
    image: prominendt/icarus-dev:arm-demo-detector
    container_name: icarus-detector
    devices:
      - /dev/video0:/dev/video0
    runtime: nvidia
    privileged: true
    entrypoint: 
      - "python3"
      - "-m"
      - "src.detector.entrypoints.gstreamer_app"