version: "3.8"

services:
  icarus-edge-detector:
    image: cricarusprod001.azurecr.io/icarus-edge-detector
    container_name: icarus-edge-detector
    devices:
      - /dev/video0:/dev/video0
    runtime: nvidia
    privileged: true
    volumes:
      - ${PWD}/icarus-edge-detector/src:/home/docker_user/src
      - ${PWD}/assets:/home/docker_user/assets
    entrypoint: 
      - /home/docker_user/scripts/start.sh
      - ${INFERENCE_MODEL}

