version: "3.8"

services:
  icarus-detector:
    image: cricarusprod001.azurecr.io/icarus-edge-detector
    container_name: icarus-detector
    devices:
      - /dev/video0:/dev/video0
    runtime: nvidia
    privileged: true
    volumes:
      - icarus-edge-detector/src:/home/docker_user/src
      - icarus-edge-detector/assets:/home/docker_user/assets
    # entrypoint: 
    #   - "python3"
    #   - "-m"
    #   - "src.detector.entrypoints.gstreamer_app"
