version: "3.8"

services:
  icarus-edge-detector:
    image: cricarusdev.azurecr.io/icarus-edge-detector
    container_name: icarus-edge-detector
    volumes:
      - ./assets:/home/docker_user/assets:ro
      - /tmp/argus_socket:/tmp/argus_socket
    environment:
      - VIDEO_OUTPUT_HEIGHT=2464
      - VIDEO_OUTPUT_WIDTH=3264
      - VIDEO_OUTPUT_FRAMERATE=21
      - REMOTE_IP_ADDRESS=${REMOTE_IP_ADDRESS}
      - REMOTE_PORT=${REMOTE_PORT}
      - REMOTE_META_DATA_SENDER_PORT=${REMOTE_META_DATA_SENDER_PORT}
      - REMOTE_META_DATA_SENDER_USERNAME=${REMOTE_META_DATA_SENDER_USERNAME}
      - REMOTE_META_DATA_SENDER_PASSWORD=${REMOTE_META_DATA_SENDER_PASSWORD}
      - META_DATA_SENDER=iot_edge
    entrypoint:
      - /home/docker_user/scripts/start.dev.sh
    restart: always