version: "3.8"

services:
  icarus-edge-detector:
    build:
      context: icarus-edge-detector
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=${BASE_IMAGE}
    image: ${CONTAINER_REGISTRY}/icarus-edge-detector:${BUILD_VERSION:-latest}