version: "3.8"

services:
  icarus-edge-detector:
    build:
      context: icarus-edge-detector
      dockerfile: Dockerfile
    image: cricarusprod001.azurecr.io/icarus-edge-detector

  icarus-edge-sender:
    build:
      context: icarus-edge-sender
      dockerfile: Dockerfile
    image: cricarusprod001.azurecr.io/icarus-edge-sender

  icarus-edge-redis:
    build:
      context: icarus-edge-redis
      dockerfile: Dockerfile
    image: cricarusprod001.azurecr.io/icarus-edge-redis