FROM nvcr.io/nvidia/l4t-base:r32.7.1

ENV HOME=/home/docker_user

COPY scripts/install_dependencies.sh /opt/dependencies/install_dependencies.sh

RUN chmod +x /opt/dependencies/*.sh \
    && /opt/dependencies/install_dependencies.sh

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 \
    	&& update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2 \
	&& curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
	&& python3 get-pip.py

RUN pip install numpy==1.19.4

RUN ln -s /usr/include/aarch64-linux-gnu/cudnn_version_v8.h /usr/include/aarch64-linux-gnu/cudnn_version.h

WORKDIR /opt

RUN git clone --depth 1 --branch 4.4.0 https://github.com/opencv/opencv.git

WORKDIR /opt/opencv/build

RUN cmake \
    -D CPACK_BINARY_DEB=ON \
	-D BUILD_EXAMPLES=OFF \
    -D BUILD_opencv_python2=OFF \
    -D BUILD_opencv_python3=ON \
	-D BUILD_opencv_java=OFF \
    -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D EIGEN_INCLUDE_PATH=/usr/include/eigen3 \
	-D WITH_EIGEN=ON \
    -D ENABLE_NEON=ON \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D OPENCV_GENERATE_PKGCONFIG=ON \
    -D WITH_GSTREAMER=ON \
    -D WITH_LIBV4L=ON \
    -D WITH_OPENGL=ON \
	-D WITH_OPENCL=OFF \
	-D WITH_IPP=OFF \
    -D WITH_TBB=ON \
	-D WITH_QT=OFf \
	-D BUILD_TIFF=ON \
	-D BUILD_PERF_TESTS=OFF \
	-D BUILD_TESTS=OFF ..

RUN make -j4

RUN make install