FROM nvcr.io/nvidia/l4t-tensorflow:r32.7.1-tf2.7-py3

ENV HOME=/home/docker_user

COPY scripts/install_dependencies.sh /opt/dependencies/install_dependencies.sh

RUN chmod +x /opt/dependencies/*.sh \
    && /opt/dependencies/install_dependencies.sh

RUN ln -s /usr/include/aarch64-linux-gnu/cudnn_version_v8.h /usr/include/aarch64-linux-gnu/cudnn_version.h

COPY --from=cricarusprod001.azurecr.io/icarus-edge-l4t-base:r32.7.1 /opt /opt

WORKDIR /opt/opencv/build

RUN make install